plugins {
    alias(libs.plugins.androidApplication) apply false
    alias(libs.plugins.androidLibrary) apply false
    alias(libs.plugins.spotbugs) apply false
    alias(libs.plugins.navigationSafeargs) apply false
}

repositories {
    google()
    mavenCentral()
}

allprojects {
    group = 'org.hammock-sync'
    version = new File(rootDir, 'VERSION').text.trim()
    description = """hammock-sync"""
    //if the version says "snapshot" anywhere assume it is not a release
    ext.isReleaseVersion = !version.toUpperCase(Locale.ENGLISH).contains("SNAPSHOT")
}
