plugins {
    id 'org.hammock.java-library'
    id 'org.hammock.maven-publishing'
    id 'org.hammock.test-conventions'
    id 'org.hammock.spotbugs'
}

dependencies {
    implementation project(':datastore-core')
    implementation libs.sqlite4java

    testImplementation libs.hamcrestAll
    testImplementation libs.junit
    testImplementation libs.mockitoAll
    testImplementation libs.commonsValidator
    testImplementation project(path: ':datastore-core', configuration: 'testUtilities')
}

tasks.register('copyFixtures', Copy) {
    from '../fixture'
    into 'fixture'
}

tasks.withType(Test).configureEach {
    systemProperty "sqlite4java.library.path", "./native"
}

hammockMaven {
    name = 'Hammock Sync JavaSE support library'
    description = 'JavaSE support for Hammock Sync Library'
}
