plugins {
    id 'org.hammock.android-library'
    id 'org.hammock.maven-publishing'
    id 'org.hammock.test-conventions'
}

android {
    namespace = 'org.hammock.sync.encrypt'
    testNamespace = 'org.hammock.sync.test'
    sourceSets {
        androidTest {
            java.exclude '**/KeyManagerTests*'
        }
    }
}

dependencies {
    implementation "${libs.sqlcipher.get()}@aar"
    implementation libs.sqlite
    api project(':datastore-android')
    api project(':datastore-core')

    implementation libs.jacksonDatabind
    implementation libs.commonsCodec
    implementation libs.commonsIo

    androidTestImplementation libs.hamcrestAll
    androidTestImplementation libs.junit
    androidTestImplementation libs.androidxTestJunit
    androidTestImplementation libs.androidxTestRunner
    androidTestImplementation libs.mockito
    androidTestImplementation libs.dexmakerMockitoInline
}

hammockMaven {
    publicationName = 'release'
    componentName = 'release'
    name = 'Hammock Sync Android Encription Library'
    description = 'Android encripted storage implementation for the Hammock Sync Library'
}
