plugins {
    id 'org.hammock.android-library'
    id 'org.hammock.maven-publishing'
    id 'org.hammock.test-conventions'
}

android {
    namespace = 'org.hammock.sync'
}

dependencies {
    api project(':datastore-core')
    implementation libs.jacksonDatabind
    implementation libs.commonsCodec
    implementation libs.commonsIo

    androidTestImplementation libs.hamcrestAll
    androidTestImplementation libs.junit
    androidTestImplementation libs.androidxTestJunit
    androidTestImplementation libs.androidxTestRunner
    androidTestImplementation libs.mockito
    androidTestImplementation libs.dexmakerMockitoInline
}

hammockMaven {
    publicationName = 'release'
    componentName = 'release'
    name = 'Hammock Sync Android Library'
    description = 'Android implementation for the Hammock Sync Library'
}
