plugins {
    id 'org.hammock.java-library'
    id 'org.hammock.maven-publishing'
    id 'org.hammock.test-conventions'
    id 'org.hammock.spotbugs'
}

dependencies {
    implementation libs.jacksonDatabind
    implementation libs.commonsCodec
    implementation libs.commonsIo
    compileOnly libs.okhttpUrlconnection

    testImplementation libs.hamcrestAll
    testImplementation libs.junit
    testImplementation libs.mockito
    testImplementation libs.commonsValidator
    testImplementation libs.toxiproxy
    testImplementation project(':datastore-javase')
}

tasks.register('copyFixtures', Copy) {
    from '../fixture'
    into 'fixture'
}

tasks.withType(Test).configureEach {
    dependsOn copyFixtures
    systemProperty "sqlite4java.library.path", "../datastore-javase/native"
}

test {
    useJUnit {
        excludeCategories \
            'org.hammock.common.RequireRunningCouchDB', \
            'org.hammock.common.RequireRunningProxy'
    }
}

tasks.register('integrationTest', Test) {
    dependsOn tasks.named('testClasses')
    useJUnit {
        excludeCategories 'org.hammock.common.RequireRunningProxy'
    }
}

tasks.register('unreliableNetworkTest', Test) {
    dependsOn tasks.named('testClasses')
    systemProperty 'test.with.specified.couch', true
    systemProperty 'test.couch.port', 8000
    systemProperty 'test.couch.proxy.admin.port', 8474
    systemProperty 'test.couch.proxy.target.port', 5984
    systemProperty 'http.keepAlive', false
    filter {
        includeTestsMatching 'org.hammock.sync.internal.replication.Unreliable*.*'
    }
}

javadoc {
    include("**/http/*")
    include("**/http/interceptors/*")
    exclude("**/http/Version.java")
}

hammockMaven {
    name = 'Hammock Sync Core Library'
    description = 'Main logic for the Hammock Sync Library'
}

configurations {
    testUtilities.extendsFrom testImplementation
}

tasks.register('testUtilitiesJar', Jar) {
    archiveClassifier = 'test-utils'
    from sourceSets.test.output
}

artifacts {
    testUtilities testUtilitiesJar
}
